# This is a basic workflow to help you get started with Actions

name: Compile for review

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Compile thesis
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./compile-for-linux
          
      - name: Rename pdf file
        run: sudo cp ./output/tesi.pdf ./output/TesiBrescanzinLorenzo.pdf
        
      - name: Upload thesis file to Google Drive folder
        uses: Jodebu/upload-to-drive@master
        with:
          target: ./output/TesiBrescanzinLorenzo.pdf
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          folder: 1lPjwZB3X8swZLAJA1agvfxE1mMt1KSj5
